apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fitness
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fitness
  template:
    metadata:
      labels:
        app: fitness
    spec:
      containers:
      - name: fitness
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 4000
