replicaCount: 3
image:
  repository: devabayomi/fitness
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 4000
ingress:
  enabled: true
  host: fitness.devopsin.name.ng
